services:
  - type: web
    name: neuroscan
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "3"
      - key: TF_ENABLE_ONEDNN_OPTS
        value: "0"
